language: python

python: 3.6

branches: master

install:
  - pip install mkdocs mkdocs-material

script: true

before_deploy:
  - mkdocs build --verbose --clean --strict

# Output mkdocs and mkdocs-material versions for local debugging
after_deploy:
  -  pip show mkdocs
  -  pip show mkdocs-material

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: site
 on:
   branch: master

# Only build on master; changes to gh-pages are irrelevant
branches:
  only:
    - master
